candidate_labels = [
    "democracy", "authoritarianism", "geopolitics", "international relations", "diplomacy", 
    "space exploration", "astrophysics", "quantum computing", "quantum physics", 
    "genomics", "epidemiology", "public health", "mental health", "neuroscience", 
    "psychopharmacology", "clinical trials", "medical ethics", "bioethics", 
    "climate change", "biodiversity", "conservation", "renewable energy", 
    "fossil fuels", "urban planning", "sustainable development", 
    "corporate social responsibility", "consumer behavior", "branding", 
    "product management", "supply chain", "e-commerce", "digital marketing", 
    "social media", "influencer marketing", "crowdfunding", "private equity", 
    "hedge funds","AI", "commodities", "foreign exchange", "derivatives", 
    "financial technology", "fintech", "cryptoeconomics", "cyber law", 
    "intellectual property", "patent law", "corporate law", "family law", 
    "environmental law", "tax law", "constitutional law", "civil rights", 
    "labor law", "public policy", "elections", "campaigns", "polling", 
    "voting rights", "political theory", "political philosophy", "international law", 
    "war crimes", "human rights", "migration", "refugees", "social justice", 
    "racial justice", "gender equality", "LGBTQ rights", "disability rights", 
    "indigenous rights", "women's rights", "children's rights", "elder care", 
    "globalization", "poverty", "inequality", "social welfare", "public finance", 
    "monetary policy", "fiscal policy", "taxation", "budgeting", "government spending", 
    "economic development", "industrial policy", "agricultural policy", "trade policy", 
    "innovation policy", "technology policy", "media studies", "journalism ethics", 
    "propaganda", "disinformation", "fake news", "censorship", "media literacy", 
    "public relations ethics", "branding strategy", "crisis management", 
    "reputation management", "stakeholder engagement", "organizational behavior", 
    "corporate culture", "leadership", "team dynamics", "employee engagement", 
    "talent management", "diversity and inclusion", "workplace wellness", 
    "occupational health", "industrial safety", "labor relations", "collective bargaining", 
    "automation", "digital transformation", "smart cities", "urbanization", 
    "rural development", "telecommunications", "internet infrastructure", 
    "satellite communications", "mobile technology", "5G technology", 
    "wireless networks", "cloud infrastructure", "data privacy", "data protection", 
    "internet governance", "net neutrality", "cyber espionage", "cyber warfare", 
    "cyber crime", "artificial general intelligence", "strong AI", "machine ethics", 
    "explainable AI", "AI alignment", "robot ethics", "autonomous systems", 
    "drones", "self-driving cars", "digital identity", "digital currency", 
    "online communities", "virtual goods", "augmented reality gaming", 
    "metaverse", "blockchain gaming", "biohacking", "transhumanism", 
    "life extension", "cryonics", "organ transplantation", "regenerative medicine", 
    "stem cell research", "gene therapy", "synthetic biology", "precision medicine", 
    "personalized medicine", "population genetics", "biostatistics", 
    "computational biology", "pharmacogenomics", "biometrics", "health informatics", 
    "telemedicine", "healthcare delivery", "patient safety", "medical devices", 
    "wearable technology", "smart homes", "assistive technology", "gerontechnology", 
    "palliative care", "end-of-life care", "holistic health", "complementary medicine", 
    "integrative medicine", "alternative medicine", "natural medicine", 
    "mind-body medicine", "meditation", "yoga", "tai chi", "acupuncture", 
    "chiropractic", "naturopathy", "homeopathy", "herbal medicine", 
    "dietary supplements", "functional foods", "nutraceuticals", "organic farming", 
    "permaculture", "agroecology", "food security", "food sovereignty", 
    "fair trade", "ethical consumerism", "slow food", "culinary arts", 
    "gastronomy", "wine", "beer", "spirits", "coffee", "tea", "chocolate", 
    "confectionery", "baking", "pastry arts", "plant-based diets", "veganism", 
    "vegetarianism", "pescetarianism", "flexitarianism", "keto diet", "paleo diet", 
    "intermittent fasting", "low-carb diets", "low-fat diets", "weight management", 
    "body image", "eating disorders", "sports nutrition", "performance enhancement", 
    "sports psychology", "exercise physiology", "strength training", "cardio training", 
    "endurance training", "high-intensity interval training", "crossfit", "functional fitness", 
    "yoga therapy", "pilates", "dance fitness", "martial arts", "self-defense", 
    "extreme sports", "outdoor recreation", "hiking", "camping", "fishing", "hunting", 
    "wildlife conservation", "nature photography", "birdwatching", "ecotourism", 
    "adventure travel", "luxury travel", "business travel", "budget travel", 
    "travel photography", "travel writing", "cultural tourism", "heritage tourism", 
    "food tourism", "sports tourism", "space tourism", "space law", "planetary science", 
    "exoplanets", "astrobiology", "astrochemistry", "cosmology", "dark matter", 
    "dark energy", "gravitational waves", "black holes", "neutron stars", "quasars", 
    "galaxies", "star formation", "stellar evolution", "supernovae", "nebulae", 
    "interstellar medium", "space weather", "solar physics", "space missions", 
    "space stations", "spacecraft design", "space robotics", "satellite technology", 
    "rocket science", "space tourism", "commercial spaceflight", "space policy", 
    "space law", "space ethics", "planetary defense", "asteroids", "comets", 
    "meteors", "space debris", "space colonization", "terraforming", "alien life", 
    "extraterrestrial intelligence", "UFOs", "SETI", "space art", "space history", 
    "space culture", "space exploration", "space research", "space education", 
    "space communication", "space transportation", "space security", "space economy", 
    "space tourism", "space law", "space ethics", "space culture", "space education", 
    "space research", "space exploration", "space technology", "space missions", 
    "space agencies", "space communication", "space transportation", "space logistics", 
    "space engineering", "space materials", "space architecture", "space habitats", 
    "space sustainability", "space mining", "space energy", "space agriculture", 
    "space medicine", "space health", "space psychology", "space physiology", 
    "space nutrition", "space fitness", "space tourism", "space law", "space policy", 
    "space governance", "space ethics", "space culture", "space communication", 
    "space exploration", "space research", "space technology", "space missions", 
    "space agencies", "space exploration", "space missions", "space technology", 
    "space communication", "space transportation", "space engineering", 
    "space materials", "space architecture", "space habitats", "space sustainability", 
    "space mining", "space energy", "space agriculture", "space medicine", 
    "space health", "space psychology", "space physiology", "space nutrition", 
    "space fitness", "space tourism", "space law", "space policy", "space governance", 
    "space ethics", "space culture", "space communication", "space exploration", 
    "space research", "space technology", "space missions", "space agencies"
]
